#!/bin/bash

#set -x
# exit if 1 command fails
set -e

DB_PROD=prod
DATADIR_PROD=/home/odoo/erp/data-dir
DATADIR_TEST=/home/odoo/data-dir-test

if [ $# -ne 1 ]
then
    echo "Usage : db-duplicate db_name"
    exit 1
fi

db_name=${1}

if [ "${db_name}" == "$DB_PROD" ]
then
    echo "Are you crazy ?!?"
    exit 2
fi


if psql -lqt | cut -d \| -f 1 | grep -qw ${db_name}
then
    echo "Database $db_name already exists. Delete it ? (y/n)"
    read answer_db
    if [ $answer_db == 'y' ]; then
        echo -n "Deleting database $db_name ... "
        dropdb $db_name
        echo "done."
    else
        echo "Delete the database $db_name manually and restart the script."
        exit 1
    fi
else
    echo "Database $db_name doesn't already exist."
fi

if [ -d $DATADIR_TEST/filestore/$db_name ]
then
    echo "Filestore directory $DATADIR_TEST/filestore/$db_name already exists. Will be synced"
fi

if [ -d $DATADIR_PROD/filestore/$DB_PROD ]
then
    echo "Prod filestore directory $DATADIR_PROD/filestore/$DB_PROD found."
else
    echo "Prod filestore directory $DATADIR_PROD/filestore/$DB_PROD NOT found"
    exit 1
fi

echo -n "Creating database ${db_name} ... "
createdb ${db_name}
pg_dump $DB_PROD | psql ${db_name}
echo "done."
echo -n "Updating database ${db_name} for test environnement ... "
psql -c "UPDATE ir_cron SET active=False" ${db_name}
psql -c "UPDATE ir_config_parameter SET value='TEST<br/>{db_name}' where key='ribbon.name'" ${db_name}
# Max TCP port is 65535, so I set 66000 (no constrain on Odoo)
psql -c "UPDATE ir_mail_server SET smtp_port=66000" ${db_name}
echo "done."

echo -n "Rsync filestore from $DATADIR_PROD/filestore/$DB_PROD to $DATADIR_TEST/filestore/$db_name ... "
rsync -av --delete-after --safe-links $DATADIR_PROD/filestore/$DB_PROD/* $DATADIR_TEST/filestore/$db_name
echo "done."

exit 0
